services:
   web:
      container_name: server-api-flask
      hostname: server-api-flask
      build: .
      ports:
         - "5000:5000"
      volumes:
         - .:/code
      networks:
         - arquivos-docker_default

networks:
   arquivos-docker_default:
      external: true
